services:
  mongo:
    image: mongo:7
    container_name: invoices_mongo
    restart: unless-stopped
    command: ["--wiredTigerCollectionBlockCompressor=zstd"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    env_file: .env
    environment:
      MONGO_URI: mongodb://mongo:27017
    depends_on:
      - mongo
    ports:
      - "8000:8000"

volumes:
  mongo_data:
